# frozen_string_literal: true

source 'https://rubygems.org'
ruby '3.2.2'

gem 'activerecord', '~> 8.0'
gem 'dotenv'
gem 'pg', '~> 1.6'
gem 'pry'
gem 'rake'
gem 'rspec'
gem 'factory_bot', '~> 6.5'
gem 'rubocop', require: false
gem 'schwab_rb', '~> 0.3.11'
gem 'sqlite3', '~> 2.1'
gem 'timecop'
gem 'gruff'
gem 'pqueue'
gem 'mcp'
gem 'clockwork'
gem 'sidekiq'
gem 'rubyzip'
gem 'zlib'
gem 'matrix'
gem 'nokogiri'
gem 'aws-sdk-s3', '~> 1'