module StrategyTypes
  CALL = 'CALL'
  PUT = 'PUT'
  VERTICAL_SPREAD = 'VERTICAL_SPREAD'
  IRON_CONDOR = 'IRON_CONDOR'
  NULL_STRATEGY = 'NULL_STRATEGY'
end

module OrderStatuses
  FILLED = 'FILLED'.freeze
  CANCELED = 'CANCELED'.freeze
  WORKING = 'WORKING'.freeze
  REJECTED = 'REJECTED'.freeze
  ACCEPTED = 'ACCEPTED'.freeze
  REPLACED = 'REPLACED'.freeze
  PENDING_ACTIVATION = 'PENDING_ACTIVATION'.freeze
end

module EventTypes
  OPEN_IRON_CONDOR = 'OPEN_IRON_CONDOR'.freeze
  OPEN_PUT_SPREAD = 'OPEN_PUT_SPREAD'.freeze
  OPEN_CALL_SPREAD = 'OPEN_CALL_SPREAD'.freeze
  CLOSE_IRON_CONDOR = 'CLOSE_IRON_CONDOR'.freeze
  CLOSE_PUT_SPREAD = 'CLOSE_PUT_SPREAD'.freeze
  CLOSE_CALL_SPREAD = 'CLOSE_CALL_SPREAD'.freeze
end
