default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: db/platypi.sqlite3

development:
  <<: *default
  database: db/platypi_dev.sqlite3

test:
  <<: *default
  database: db/platypi_test.sqlite3