default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: db/OptionsTrader.sqlite3

development:
  <<: *default
  database: db/OptionsTrader_dev.sqlite3

test:
  <<: *default
  database: db/OptionsTrader_test.sqlite3