default: &default
  adapter: postgresql
  encoding: unicode
  pool: 15
  timeout: 5000
  prepared_statements: false
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  username: <%= ENV['DATABASE_USER'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'postgres' %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'options_trader_db_dev' %>

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  prepared_statements: false
  database: options_trader_db_test
  username: postgres
  password:
  host: localhost
  port: 5432