#!/usr/bin/env ruby

require_relative "../lib/options_trader"
require "dotenv/load"

required_vars = [
  'SCHWAB_API_KEY',
  'SCHWAB_APP_SECRET',
  'SCHWAB_CALLBACK_URI',
  'TOKEN_PATH'
]
missing_vars = required_vars.select { |var| ENV[var].nil? || ENV[var].empty? }

unless missing_vars.empty?
  exit 1
end

OptionsTrader::MCP::Server.new.start